name: Sync Overleaf with Zotero
on: push
permissions: write-all
jobs:
  run:
    name: Sync Overleaf with Zotero
    runs-on: ubuntu-latest
    env:
      ZOTERO_API_KEY: ${{ secrets.ZOTERO_API_KEY }}
      ZOTERO_AUTO_DIR: zotero-auto
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - run: echo "zoterotex" >> requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r requirements.txt

      - run: mkdir -p zotero-auto

      - name: Sync BibTeX
        run: zoterotex sync group 4816962 $ZOTER_AUTO_DIR/group-library.bib

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Automated github action
          author_email: mail@example.com
          message: 'Updated BibTeX files'
          add: '$ZOTERO_AUTO_DIR'
